env:
 devs
spring:
  application:
    name: api-agteway
  cloud:
    config:
      discovery:
        service-id: config-server
        enabled: true
      profile: dev
 
server:
  port: 5050
 
zuul:
  routes:
    myProduct:  
      path: /myProduct/**
      serviceId: product
      sensitiveHeaders:  


management:
  security:
    enabled: false
