env:
 devs
server:
  port: 4040
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: YHP836143
    url: jdbc:mysql://127.0.0.1/sell?characterEncoding=utf-8&useSSL=false
    jpa:
      show-sql: true
    jackson:
      default-property-inclusion: non_default
